struct TileData {
    id: int,
    name: string,
    time: int,
}

import { VerticalBox, HorizontalBox, Button, GridBox, CheckBox } from "std-widgets.slint";
import { Setting } from "./setting.slint";
import { ListMacros } from "./list-macros.slint";
 

export component MainWindow inherits Window {

    property <color> primary_color:#1C1B1F;
    property <bool> subWindowsOpened: false;
    property <bool> showSetting: false;
    property <bool> showListMacros: false;
    property <int> id: 0;
    
    in-out property <bool> recording: false;
    in-out property <bool> repeat: false;
    in-out property <string> key_stop: "Q";
    in-out property <string> repeat_each:"1";
    in-out property <bool> auto_stop: false;
    in-out property <string> auto_stop_clicks:"1";
    in property <string> time: "00:00:00";
    in-out property <[TileData]> tile_data: [];
    
    callback move_windows();
    callback record();
    callback set_repeat(bool);
    callback set_auto_stop(bool);
    callback set_repeat_each(string);
    callback set_key_stop(string);
    callback set_auto_stop_clicks(string);
    callback replay(int);
    callback refresh_list();
    callback delete_macro(int);
    callback close_windows();

    width: 400px;
    height: subWindowsOpened ? 210px : 50px;
    no-frame: true;
    background: transparent;

    VerticalLayout {
        alignment: LayoutAlignment.start;
        Rectangle {
            padding-bottom: 20px;
            width: 400px;
            height: 50px;
            background: #D9D9D9;
            border-top-left-radius: 5px;
            border-top-right-radius: 5px;
            border-bottom-left-radius: subWindowsOpened ? 0px : 5px;
            border-bottom-right-radius: subWindowsOpened ? 0px: 5px;
            Image {
                y: 14px;
                x: 10px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/drag_handle_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                TouchArea {
                    moved => {
                        move_windows();
                    }
                }
            }

            Image {
                y: 14px;
                x: parent.width - 32px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/close_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                TouchArea {
                    clicked => {
                        close_windows();
                    }
                }
            }

            Image {
                y: 14px;
                x: 50px;
                height: 24px;
                width: 24px;
                source: recording ? @image-url("icons/highlight_mouse_cursor_24dp_F60004_FILL0_wght400_GRAD0_opsz24.png") : @image-url("icons/highlight_mouse_cursor_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                TouchArea {
                    clicked => {
                        if (!recording) {
                            subWindowsOpened = false;
                            showSetting = false;
                            showListMacros = false;
                            record();
                            recording = true;
                        }
                    }
                }
            }

            Image {
                y: 14px;
                x: 90px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/contract_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                TouchArea {
                    clicked => {
                        if showListMacros {
                            subWindowsOpened = false;
                            showListMacros = false;
                           
                            
                        }else{
                            subWindowsOpened = true;
                            showSetting = false;
                            refresh_list();
                            showListMacros = true;
                        }
                        
                    }
                }
            }

            Image {
                y: 14px;
                x: 130px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/settings_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                TouchArea {
                    clicked => {
                        if showSetting {
                            showSetting = false;
                            subWindowsOpened = false;
                        }else{
                            subWindowsOpened = true;
                            showListMacros = false;
                            showSetting = true;
                        }
                        
                    }
                }
            }

            Text {
                y: 12px;
                x: 200px;
                text <=> time;
                font-size: 24px;
                color: primary_color;
            }
        }
        if showSetting: Setting {

            // functions callbacks
            set_repeat (repeat) => {
                set_repeat(repeat);}

            set_repeat_each (repeat_each) => {
                set_repeat_each(repeat_each);}

            set_key_stop (keyStop) => {
                set_key_stop(keyStop);}

            set_auto_stop (auto_stop) => {
                set_auto_stop(auto_stop);}

            set_auto_stop_clicks (auto_stop_each) => {
                set_auto_stop_clicks(auto_stop_each);} 

            //variables
                repeat <=> repeat;
                repeat_each <=> repeat_each;
                key_stop <=> key_stop;
                auto_stop <=> auto_stop;
                auto_stop_clicks <=> auto_stop_clicks;
        }
        if showListMacros:  ListMacros{
            replay(id) => {
                replay(id);
            }
            delete_macro(id) => {
                delete_macro(id);
            }
            tile_data <=> tile_data;
        }
     
    }
}
