struct TileData {
    id: int,
    name: string,
    time: string,
}

import { ListView } from "std-widgets.slint";


export component ListMacros inherits Rectangle {

    in-out property <[TileData]> tile_data;

    callback replay(int);


    width: 400px;
    height: 160px;
    background: #f3f3f3;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
    ListView {
        y: 0px;
        x: 0px;
        width: 400px;
        height: 160px;

        for data in tile_data: Rectangle {
            height: 30px;
            background: touch.has-hover || touchRun.has-hover || touchDel.has-hover ? #bdd9f5 : #f3f3f3;
            width: parent.width;
            touch := TouchArea { }

            Text {
                padding: 30px;
                x: 15px;
                text: data.name;
                color: #f3f3f3;
            }

            Image {
                y: 4px;
                x: 340px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/motion_play_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                touchRun := TouchArea {
                    clicked => {
                        debug("clicked run!!");
                        replay(data.id);
                    }
                }
            }

            Image {
                y: 4px;
                x: 370px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/delete_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                touchDel := TouchArea {
                    clicked => {
                        debug("clicked del!!");
                    }
                }
            }
        }
    }
}
