import { ListView } from "std-widgets.slint";


export component ListMacros inherits Rectangle {
 

    width: 400px;
    height: 160px;
    background: #f3f3f3;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
    ListView {
        y:0px;
        x:0px;
        width: 400px;
        height: 160px;

        for data in [
            { id: 1, text: "Jan 31, 2025 (00) | 09:50:25 | R:003 | L: 000", color: #1d1d1d, bg: #eeeeee},
            { id: 2, text: "Jan 31, 2025 (01) | 00:00:53 | R:003 | L: 000", color: #1d1d1d, bg: #d1dcdf},
            { id: 3, text: "Jan 31, 2025 (02) | 00:50:25 | R:003 | L: 000", color: #1d1d1d, bg: #eeeeee},
        ] : 
       
        Rectangle {
            height: 30px;
            background:  touch.has-hover || touchRun.has-hover || touchDel.has-hover ? #bdd9f5 : data.bg;
            width: parent.width;
            touch := TouchArea {}

            Text {
                padding: 30px;
                x: 15px;
                text: data.text;
                color: data.color;
            }

            Image {    
                y: 4px;
                x: 340px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/motion_play_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                touchRun := TouchArea { 
                    clicked => {
                        debug("clicked run!!");
                    }
                }
                
            }
            Image {
                y: 4px;
                x: 370px;
                height: 24px;
                width: 24px;
                source: @image-url("icons/delete_24dp_1C1B1F_FILL0_wght400_GRAD0_opsz24.png");
                touchDel := TouchArea { 
                    clicked => {
                        debug("clicked del!!");
                    }
                }
            }
        }
    }
}