import { VerticalBox, HorizontalBox, Button, GridBox, CheckBox, TextEdit, SpinBox, Palette, LineEdit } from "std-widgets.slint";


export component Setting inherits Rectangle {
    property <color> primary_color: #1C1B1F;
    property <string> each: "1";
    property <bool> PressKey: false;
    property <image> check: @image-url("icons/check_box_outline_blank_18dp_1C1B1F_FILL0_wght400_GRAD0_opsz20.png");

    width: 400px;
    height: 160px;
    background: #f3f3f3;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
    VerticalLayout {
        HorizontalLayout {
            padding: 20px;
            alignment: LayoutAlignment.start;
            Text {
                text: "Repeat:";
                color: primary_color;
                font-size: 16px;
            }
            
            CheckBox {
                width: 25px;
                height: 20px;
                padding: 0px;
            }

            Rectangle {
                width: 15px;
            }

            Text {
                text: "Each:";
                color: primary_color;
                font-size: 16px;
            }

            LineEdit {
                width: 50px;
                height: 20px;
                text <=> each;
                font-size: 16px;
                input-type: number;
                edited(text) => {
                    
                }
               
            }
        }
        HorizontalLayout {
            alignment: LayoutAlignment.start;
            padding-left: 20px;
            padding-bottom: 20px;
            Text {
                text: "Key Stop:";
                color: primary_color;
                font-size: 16px;
            }
            Rectangle {
                width: 45px;
                height: 29px;
                Image {
                    y:0px;
                    x: 0px;
                    height: 29px;
                    width: 45px;
                    source: @image-url("icons/keymod.png");
                    TouchArea {
                        clicked => {
                           PressKey = true;
                        }
                    }
                }
                Text {
                    text: "ctrl";
                    color: #888888;
                }
            }
            Rectangle {
                width: 28px;
                height: 28px;
                Image {
                    y:0px;
                    x: 0px;
                    height: 28px;
                    width: 28px;
                    source: @image-url("icons/key.png");
                    TouchArea {
                        clicked => {
                           PressKey = true;
                        }
                    }
                }
                Text {
                    text: "Q";
                    color: #888888;
                }
            }
            Text {
                visible: PressKey;
                text: "  Press the Control + Key...";
                color: #036ae0;
                font-size: 14px;
            }
        }
        HorizontalLayout {
            alignment: LayoutAlignment.start;
            padding-left: 20px;
            padding-bottom: 20px;
            Text {
                text: "Auto Stop:";
                color: primary_color;
                font-size: 16px;
            }
            CheckBox {
                width: 25px;
                height: 20px;
                padding: 0px;
            }
            Text {
                text: "  After:";
                color: primary_color;
                font-size: 16px;
            }
            LineEdit {
                width: 50px;
                height: 20px;
                text: "1";
                font-size: 16px;
                input-type: number;
                edited(text) => {
                    
                }
               
            }
            
            Text {
                text: "Clicks";
                color: primary_color;
                font-size: 16px;
            }
            
        }
    }
}
